---
title: "p8105_hw1_th3072"
Author: Tianyou He
output: github_document
date: "2023-09-20"
---

```{r}
library(moderndive)
library(tidyverse)
data("early_january_weather")
```

#Problem 1

## Variable of Dataset:
day, hour, temp, dewp,humid,wind_dir, wind_speed,wind_gust,precip, pressure, visib, time_hour


## Size of the Dataset:
```{r}
nrow(early_january_weather)
ncol(early_january_weather)
```
## Mean of temp
```{r}
mean(early_january_weather$temp)
```

## Scatterplot of time_hour and temp
```{r yx_scatter}
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = "humid")) + geom_point()
ggsave("Problem_1_scatter.pdf")
```

#Problem 2

```{r}
random_sample = rnorm(10)
length(random_sample)

logical_vector <- random_sample >0

character_vector <- letters[1:10]

factor_vector <- factor(rep(c("red", "green","blue"), times = c(4,2,4)))
```

```{r}
df <- data.frame(random_sample, logical_vector, character_vector, factor_vector)
```

```{r}
mean(random_sample)
mean(pull(df,logical_vector))
mean(pull(df,character_vector))
mean(pull(df,factor_vector))
```


```{r}
numeric_logical <- as.numeric(logical_vector)
numeric_logical <- as.numeric(character_vector)
numeric_logical <- as.numeric(factor_vector)
```

